on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Black
      run: |
        sudo pip install black
    - name: Run Black
      run: |
        black -l 88 src tests --check
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -s --disable-pytest-warnings
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-outputs
        path: tests/outputs/*csv
        retention-days: 5